CREATE TABLE EMPLOYEE16 (
EMPLOYEE_ID NUMBER(6,0), 
NAME VARCHAR2(20), 
SALARY NUMBER(8,2) 
);

INSERT INTO EMPLOYEE16(EMPLOYEE_ID,NAME,SALARY) VALUES(100,'Jennifer',4400);
INSERT INTO EMPLOYEE16(EMPLOYEE_ID,NAME,SALARY) VALUES(100,'Jennifer',4400);
INSERT INTO EMPLOYEE16(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000);
INSERT INTO EMPLOYEE16(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000);
INSERT INTO EMPLOYEE16(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000);
INSERT INTO EMPLOYEE16(EMPLOYEE_ID,NAME,SALARY) VALUES(102,'Pat',6000);
INSERT INTO EMPLOYEE16(EMPLOYEE_ID,NAME,SALARY) VALUES(102,'Pat',6000);
INSERT INTO EMPLOYEE16(EMPLOYEE_ID,NAME,SALARY) VALUES(103,'Den',11000);

SELECT * FROM EMPLOYEE16;

select distinct emp.* from employee16 emp;

SELECT ROWID,
 EMPLOYEE_ID,
 NAME,SALARY, 
 ROW_NUMBER() OVER(PARTITION BY EMPLOYEE_ID,NAME,SALARY ORDER BY 
EMPLOYEE_ID) AS ROW_NUMBER 
FROM EMPLOYEE16;

select emp.*, dense_rank() over(partition by deptno order by sal desc) as sal_rank from emp;


select * from dba_users;


create user c##satya identified by qearmq312Q##OUWR;
grant all privileges to c##satya;











